id: I282C30CF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T11:52:36+00:00'
last_modified: '2022-06-07T21:10:04.634815+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12538
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་ཡོན་ཏན་ཀུན་འབྱུང་གི་དབང་ཆོས་ཕྱོགས་བསྒྲིགས་བཀླག་ཆོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4860':
      image_group_id: I1KG12568
      title: ''
      total_pages: 102
      order: 1
      base_file: 4860.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
