id: P004219
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12538
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་ཡོན་ཏན་ཀུན་འབྱུང་གི་དབང་ཆོས་ཕྱོགས་བསྒྲིགས་བཀླག་ཆོག
  author: ''
  volumes:
    e679dfb8e44f42d3a85a0e44c8a38339:
      image_group_id: I1KG12568
      title: ''
      volume_number: 1
      total_pages: 102
