id: P004219
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG12538
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་ཡོན་ཏན་ཀུན་འབྱུང་གི་དབང་ཆོས་ཕྱོགས་བསྒྲིགས་བཀླག་ཆོག
  author: ''
  volumes:
    e679dfb8e44f42d3a85a0e44c8a38339:
      image_group_id: I1KG12568
      title: ''
      volume_number: 1
      total_pages: 102
      base_file: v001.txt
